#!/bin/sh
# Reset the System Clock to UTC if the hardware clock from which it
# was copied by the kernel was in localtime.

dev=$1

if [ -f /etc/default/rcS ] ; then
    . /etc/default/rcS
fi

# These defaults are user-overridable in /etc/default/hwclock
BADYEAR=no
HWCLOCKACCESS=yes
HWCLOCKPARS=
HCTOSYS_DEVICE=rtc0
if [ -f /etc/default/hwclock ] ; then
    . /etc/default/hwclock
fi

/sbin/hwclock -v --rtc=$dev --hctosys && (
    # Note 'touch' may not be available in initramfs
    > /run/udev/hwclock-set

    mkdir -p /run/systemd/timesync/
    > /run/systemd/timesync/synchronized
)
